### ISSUE TITLE
Size Classes

### ISSUE THREAD

**Issue by ed-mejia** [ykyouhei/KYShutterButton#10]
Hi there, this control is really great, unfortunately does not work well when using size classes if you set an initial size class any/any with a particular size and then you want to set a different size when in compact/regular size class it does not update according to the actual size class.

**Comment by ykyouhei** [comment]
@ed-mejia Hi! Supported size class! https://github.com/ykyouhei/KYShutterButton/releases/tag/1.0.4

**Comment by ed-mejia** [comment]
Hey!... @ykyouhei 

I was looking around and seems it's not working quite right yet... I have the same issue with another lib and I tried to look at your "support size classes" commit  but couldn't find anything that give me a hint about it...

You can check this screen from the actual sample project to find out is not being displayed correctly on the simulator, but it is on the IB screen 

<img width="1222" alt="screen shot 2016-07-24 at 2 36 20 pm" src="https://cloud.githubusercontent.com/assets/7431094/17081872/6a2ba7b4-51ac-11e6-8b65-e7f5ce471e64.png">

**Comment by ykyouhei** [comment]
@ed-mejia
Hi! Fixed a bug. https://github.com/ykyouhei/KYShutterButton/commit/71f1140b5620a3eb67b04efe544363c9ea27034d
https://github.com/ykyouhei/KYShutterButton/releases/tag/1.0.4

**Comment by ed-mejia** [comment]
Works great! thanks @ykyouhei 👍
